### ISSUE TITLE
Need more info

### ISSUE THREAD

**Issue by behuda** [ajdnik/decrypo#1]
brew has failing, so tried it locally by manually downloading
`./decrypo -output "./outFolder"`
Tried with the above command, but the output was just one line

`617 / 617 [----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% ? p/s`

If run without sudo command it deletes all files from folder
`~/Library/Application\ Support/com.pluralsight.pluralsight-mac/ClipDownloads`
 
Subtitles can also extracted from the db folder.

**Comment by behuda** [comment]
```
const { createReadStream, createWriteStream } = require('fs');

const stream = createReadStream('./inp.psv');
const writer = createWriteStream('./output.mp4');

stream.on('data', data => {
  stream.pause();
  writer.write(data.map(b => b ^ 101)); 
  stream.resume();
}) 

```

done with changes, how did u figured it out that it should be xor' with 101

**Comment by ajdnik** [comment]
Hey @behuda, sorry for the late reply. Yes, the code you posted is the bare minimum to decrypt videos downloaded through the Mac version of the Pluralsight app.

I wasn't the one to figure out how to decrypt the videos. I just saw that no one created a solution that covers both MacOS and Windows versions. [Here's](https://andorian.blogspot.com/2017/08/de-obfuscate-videos-from-pluralsight.html) an article explaining how someone figured it out for MacOS.

I have a couple of follow up questions regarding the problems you described in your initial issue request. I'm aware that I need to fix Homebrew installer, sorry I haven’t gotten to fix it yet.
If I understood correctly you mean that if you ran the command line without sudo it deleted all of the files in your `~/Library/Application\ Support/com.pluralsight.pluralsight-mac/ClipDownloads` folder?

I'm aware that subtitles are also stored in the sqlite database, that's a good idea for a future improvement of the utility.

**Comment by behuda** [comment]
@ajdnik Thanks for ur reply.  I tried again, by clicking the executable directly from finder, and it works fine.
Maybe I can write node script to extract subtitles and places in correct directory.

**Comment by ajdnik** [comment]
I've started working on the subtitles feature. You can see the progress on [the captions branch](/ajdnik/decrypo/tree/captions).

**Comment by ajdnik** [comment]
The captions are now apart of the master branch feel free to check out the code if you wish to replicate it in Node.JS.
