### ISSUE TITLE
The system cannot find the path specified

### ISSUE THREAD

**Issue by RossyDoubleUnderscore** [ajdnik/decrypo#10]
`PS C:\PluralsightDecrypo> .\decrypo.exe`
`Found 185 clips in database.`
`Decrypting clips and extracting captions...`
`47 / 185 [------------------------>______________________________________________________________________] 25.41% 5 p/s`
`panic: open Pluralsight Courses\Install-and-Configure-Active-Directory-Domain-Services-in-Windows-Server-2016\5-Create-and-Manage-Active-Directory-Groups-and-Organizational-Units\10-Delegate-the-Creation-and-Management-of-Active-Directory-Groups-and-OUs.mp4: The system cannot find the path specified.`
` `
`goroutine 1 [running]:`
`main.main()`
`    d:/a/decrypo/src/github.com/ajdnik/decrypo/main.go:63 +0x86b`

I tried deleting the course that is returning this error and re-downloading it, but the error persists. Not sure if it's an error with PluralSight's information about the video, or if it's an issue with Decrypo somewhere in the decryption process.

**Comment by ajdnik** [comment]
Hi @ddr4lyfe,

this looks like you're hitting the Windows 260 character filename limitation. As a quick fix what I can suggest is that you enable the long filename support. For Windows 10 [here's](https://www.itprotoday.com/windows-10/enable-long-file-name-support-windows-10) a quick tutorial.

**Comment by RossyDoubleUnderscore** [comment]
@ajdnik I wondered if that may have been the issue, but it looks like my long filename support is already enabled. Is it a similar limitation for Go, or the compiled Windows .exe perhaps?

**Comment by ajdnik** [comment]
I've looked into it and it seems to be a problem with __Go__. I'm researching how to fix it.

**Comment by mprkins** [comment]
As a quick fix you can rename the "Pluralsight Courses" to just "p" then you are good to go!

**Comment by RossyDoubleUnderscore** [comment]
@mprkins good call on outputting to a "p" folder, it was a short enough string to finish the decryption process.

**Comment by ajdnik** [comment]
@ddr4lyfe I've just released version [0.3.3](https://github.com/ajdnik/decrypo/releases/tag/0.3.3) that fixes the issue with long Windows file paths. I've tested it on my Windows system and it works.
