### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by devKshitijJain** [ajdnik/decrypo#2]
==> Installing decrypo from ajdnik/decrypo
==> Downloading https://github.com/ajdnik/decrypo/releases/download/0.2.3/decryp
#=#=#
curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "decrypo"
Download failed: https://github.com/ajdnik/decrypo/releases/download/0.2.3/decrypo_darwin_amd64.tar.gz

**Comment by ajdnik** [comment]
Hi @devKshitijJain,

I'm sorry for the error. I've updated the Homebrew repo to use the latest release version.

**Comment by devKshitijJain** [comment]
@ajdnik Awesome thanks. Although I was able to edit directly into brew script and make it work but it will ensure no-one else will face this issue.
