### ISSUE TITLE
panic: sql: Scan error on column index 0

### ISSUE THREAD

**Issue by gitNemo** [ajdnik/decrypo#3]
Hello

After downloaded some courses, the command line bring an error;

`panic: sql: Scan error on column index 0, name "ZDETAILS": converting NULL to int is unsupported

goroutine 1 [running]:
main.main()
	/Users/runner/runners/2.165.2/work/decrypo/src/github.com/ajdnik/decrypo/main.go:59 +0x575`

**Comment by gitNemo** [comment]
Found a workaround by deleting null ZDETAILSs from the database.

**Comment by ajdnik** [comment]
Hi @gitNemo,

thanks for pointing that out. I didn't handle NULL values correctly. I've committed a fix 33d5f1bcc86e89029337799643b312d4663eee17 and I'll be pushing a new version to homebrew shortly once I'm finished with testing.

**Comment by ajdnik** [comment]
Ok, I've finished testing on my Windows system and everything works. I've pushed a new version on homebrew.

I'm not sure how exactly ZDETAILS is NULL in your database but my assumption is that the course is either invalid or it isn't downloaded locally. So for now what I've done is that the tool ignores courses/modules/clips that have NULL values.
