### ISSUE TITLE
How to delete it?

### ISSUE THREAD

**Issue by ilai1823** [ajdnik/decrypo#5]

**Comment by ajdnik** [comment]
Hi @ilai1823,

That depends on how you installed it.

If you installed it using Homebrew, then you use the same method as with any other Homebrew package. If you just want to [uninstall the package](https://docs.brew.sh/Manpage#uninstall-rm-remove-options-formula) run `brew remove decrypo`. If you want to [remove the tap](https://docs.brew.sh/Taps#the-brew-tap-command) as well run `brew untap ajdnik/decrypo`.

If you installed it using __go install__, then you can call `rm $GOPATH/bin/decrypo`.

If you just downloaded and unarchived the binaries from [GitHub's releases page](https://github.com/ajdnik/decrypo/releases) than you just need to delete the binary.

**Comment by ilai1823** [comment]
I used third method and i deleted executable file unpacked from the archive. That is enough, isn't it?

**Comment by ajdnik** [comment]
Yes, you just need to delete the executable and the archive.

**Comment by ilai1823** [comment]
I was thinking that it doesn't work, now I understood that everything works as supposed. Thank you for the tool!
