### ISSUE TITLE
Decrypted files will not play

### ISSUE THREAD

**Issue by MrSmite** [ajdnik/decrypo#7]
OS: Windows 7
decrypo version: 0.3.1

Bug:

After decrypting course, the video does not play.

Details:

The course title and module names are all correct, as well as the SRT files. But the mp4 files will not play in VLC, MPC-HC, KM Player or WMP. It seems the decryption key may have changed.

**Comment by ajdnik** [comment]
Hi @MrSmite,

Could you let me know which version of Pluralsight are you using and if the .mp4 files are empty, meaning if their file size is 0? Lastly, how did you install the tool, via the precompiled binary in the releases or via `go get`?

**Comment by mmi-mo** [comment]
Hi @ajdnik,

OS: Windows 8
decrypo version: 0.3.1 (via precompiled binary)
Pluralsight Offline Player 1.0.247.0

.mp4 files are not empty.

**Comment by Ollie-Robinson** [comment]
> Hi @MrSmite,
> 
> Could you let me know which version of Pluralsight are you using and if the .mp4 files are empty, meaning if their file size is 0? Lastly, how did you install the tool, via the precompiled binary in the releases or via `go get`?

Hi @ajdnik 

I too am having this issue:

OS: Windows 10 Pro
decrypo version: 0.3.1 (via precompiled binary)
Pluralsight Offline Player 1.0.247.0

I've had the exact same issue with another decryptor I have hence trying this one, so I can only assume they have changed something on their end.

Hope this helps.

**Comment by ajdnik** [comment]
Hmm, I've tested the precompiled binary on both Windows 8 and Windows 10 using version 0.3.1 and Pluralsight 1.0.247.0 and the videos decrypted correctly.

Would it be possible if either(@MrSmite, @mmi-mo or @Ollie-Robinson) of you could send one of the "decrypted" .mp4 files? It can be the smallest one just so I can see the difference on my machine. And when you send it if you can let me know from which course/module/clip it came from.

Thank you,
Rok

**Comment by morcibacsi** [comment]
I have the same issue as well. With the same versions as Ollie-Robinson.

Here is a sample file:
[Xamarin-Forms-The-Big-Picture-4-The-Development-Environment-4-Summary.zip](https://github.com/ajdnik/decrypo/files/4469076/Xamarin-Forms-The-Big-Picture-4-The-Development-Environment-4-Summary.zip)

The course is: Xamarin.Forms: The Big Picture
Section: The Development Environment
Clip: Summary

**Comment by ajdnik** [comment]
Hi @morcibacsi,

thanks for the clip. It looks like they updated the encryption so I'll need to do some further research. If you've downloaded videos using a previous version of the application they can be decrypted but if you've downloaded them with the newer version the tool won't work. I'll look into it.

**Comment by nstylepro** [comment]
what version is supported?  for me this was the cli output and no videos were created...
![image](https://user-images.githubusercontent.com/50114117/79122399-383d4400-7da0-11ea-8c94-1bc7f14d7dcf.png)

version of player is 1.0.246.0

**Comment by MrSmite** [comment]
Sorry for the late reply. I am using version 1.0.247.0 of the player. Some answers follow:

1. The files are not 0 byte (but I see you have a sample already)
2. I used the _go get_ method to install
3. I tried debugging the player to see if I could find the key but I'm not too good with that side of coding. Specifically I was focusing on **msmpeg2adec.dll** (loaded by the player's wmp plugin) because of its calls to various crypto functions.

No luck on my end.

**Comment by cythron** [comment]
New release of pluralsight has updated its encryption. I also had 20+ GBs of files that used new "V2 encryption" (as Pluralsight devs say). So, decrypo tries to decrypt those files using old V1 decryption, hence the files are corrupted.
 
I made the fix by reversing the code. It can decrypt both new and old versions of encryption and also fix the video that was corrupted. Please beware that my program is super laggy and annoying.

You can search "cythron/cytPSV" for the tool.

**Comment by cythron** [comment]
@MrSmite 

Since, it is a .NET executable, finding the keys is as simple as running dnSpy. You can find the keys here in case you don't want to decompile the code.

https://pastebin.com/4qVHkzs8

**Comment by ajdnik** [comment]
Thank you @cythron, I'll normalize the new keys into hex and implement it today.

**Comment by ajdnik** [comment]
I've released a new version [0.3.2](https://github.com/ajdnik/decrypo/releases/tag/0.3.2).

**Comment by cythron** [comment]
@ajdnik You're welcome!
Thanks for the new update.

**Comment by MrSmite** [comment]
Thanks to cythron and ajdnik for their quick work. Closing issue.

**Comment by henild** [comment]
@cythron i am not able to find that tool. Did you make it private?

**Comment by cythron** [comment]
@Henil 
Yes, because it was like a quick and dirty fix and was super buggy. So, if you just need to recover a damaged file, then I will make it public.

**Comment by henild** [comment]
@cythron Yes please.

**Comment by cythron** [comment]
@Henil 
I'm uploading a new repo at cythron/PsvRepair.

**Comment by MrSmite** [comment]
I haven't encountered any bugs. I decrypted a few videos and scrubbed through them and didn't see any issues. Not all the courses had SRT files but the website indicates not all courses have them anyway.
